name = "ScaledInvariantGPLVMSpectraReconstructionSpectralData"
uuid = "2b0fa9ba-9b76-4d49-aa09-907878bd84b9"
authors = ["Nikos Gianniotis <ngiann@gmail.com> and contributors"]
version = "0.0.3"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LazyArtifacts = "4af54fe1-eca0-43a8-85a7-787d91b784e3"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[compat]
Artifacts = "1.11.0"
JLD2 = "0.5.13"
LazyArtifacts = "1.11.0"
Printf = "1.11.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
